backend:
  name: git-gateway
  branch: dfrl

media_folder: '/_src/image'
public_folder: '../image'

collections:
  - name: 'pages'
    label: 'Website'
    files: 
      - label: 'Homepage'
        name: 'home'
        file: '_src/index.md'
        editor:
          preview: false
        fields:
          - { label: 'Heading', name: 'title', widget: 'string', required: false  }
          - { label: 'Body', name: 'body', widget: 'markdown', required: false }
      - label: 'Settings'
        name: 'settings'
        file: '_src/_data/meta.json'
        editor:
          preview: false
        fields:
          - { label: 'URL', name: 'url', widget: 'string' }
          - { label: 'Color', name: 'color', widget: 'string' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Author(s)', name: 'creator', widget: 'string' }
          - { label: 'Rights', name: 'rights', widget: 'string' }
          - { label: 'ISBN', name: 'identifier', widget: 'string' }

  - name: 'chapter'
    label: 'Book Content'
    folder: '_src/chapter'
    create: true
    slug: 'index'
    path: '{{title}}'
    editor:
      preview: false
    fields:
      - { label: 'Permalink', name: 'permalink', widget: 'string', required: false }
      - { label: 'Chapter Number', name: 'chapterNumber', widget: 'number', required: false }
      - { label: 'Chapter Title', name: 'title', widget: 'string' }
      - { label: 'Order', name: 'tocOrder', widget: 'number', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown', required: false }
